---
- name: Create /etc/cluster directory
  tags: ha-cluster-pacemaker
  file: path=/etc/cluster state=directory

- name: Copy fence_xvm key to all cluster nodes
  tags: ha-cluster-pacemaker
  copy: src="{{ fence_xvm_key }}" dest=/etc/cluster/fence_xvm.key owner=root group=root mode=0640

- name: Enable fence_xvm port(1229/tcp) in firewalld
  tags: ha-cluster-pacemaker
  firewalld: port=1229/tcp permanent=true state=enabled immediate=true
  when: ansible_distribution_major_version == "7" and cluster_firewall == true

- name: create fence_xvm STONITH devices
  tags: ha-cluster-pacemaker
  pcs_resource: name="fence-{{ hostvars[item]['ansible_fqdn'].split('.')[0] }}" resource_class='stonith' resource_type=fence_xvm options="pcmk_host_map={{ hostvars[item]['ansible_fqdn'].split('.')[0] }}:{{ hostvars[item]['hypervisor_hostname'] }}; op monitor interval=30s"
  with_items: '{{ play_hosts }}'
  run_once: true

- name: create fence constraints
  tags: ha-cluster-pacemaker
  pcs_constraint: constraint_type='location' resource1="fence-{{ hostvars[item]['ansible_fqdn'].split('.')[0] }}" node_name="{{ hostvars[item]['ansible_fqdn'].split('.')[0] }}" score='-INFINITY'
  with_items: '{{ play_hosts }}'
  run_once: true

# FIXME - EL6 firewall
