---
- name: enable HA/RS repository
  tags: ha-cluster-pacemaker
  command: subscription-manager repos --enable="rhel-{{ repos_type }}-for-rhel-{{ ansible_distribution_major_version }}-server-rpms"
  when: enable_repos == true

- name: enable HA/RS EUS repository
  tags: ha-cluster-pacemaker
  command: subscription-manager repos --enable="rhel-{{ repos_type }}-for-rhel-{{ ansible_distribution_major_version }}-server-eus-rpms"
  when: enable_eus_repos == true
